#include "tileMap.h"
#include <stdint.h>
#include <avr/pgmspace.h>

// Converts an RGB colour (0-255 for each component) to the internal representation.
#define COLOR(r, g, b) ((r & 0xE0) | ((b >> 3) & 0x18) | ((g >> 5) & 0x07))

#define COLOR_BLACK   COLOR(  0,   0,   0)
#define COLOR_RED     COLOR(255,   0,   0)
#define COLOR_YELLOW  COLOR(255, 255,   0)
#define COLOR_GREEN   COLOR(  0, 255,   0)
#define COLOR_CYAN    COLOR(  0, 255, 255)
#define COLOR_BLUE    COLOR(  0,   0, 255)
#define COLOR_MAGENTA COLOR(255,   0, 255)
#define COLOR_WHITE   COLOR(255, 255, 255)

#if TILE_WIDTH == 6

const uint8_t tileMap[][TILE_SIZE] PROGMEM = {
    {
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
    },
    {
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
    },
    {
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
    },
    {
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
    },
    {
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
    },
    {
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
    },
    {
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
    },
    {
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
    },
    {
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
    },
    {
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
    },
    {
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
    },
    {
        COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    ,
        COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    ,
        COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  ,
    },
};

#elif TILE_WIDTH == 8

const uint8_t tileMap[][TILE_SIZE] PROGMEM = {
    {
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  , COLOR_BLACK  ,
    },
    {
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
        COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    , COLOR_RED    ,
    },
    {
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
        COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW , COLOR_YELLOW ,
    },
    {
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  , COLOR_GREEN  ,
    },
    {
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
        COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   , COLOR_CYAN   ,
    },
    {
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   , COLOR_BLUE   ,
    },
    {
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
        COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA, COLOR_MAGENTA,
    },
    {
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
        COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  , COLOR_WHITE  ,
    },
    {
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
        COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    , COLOR_BLACK  , COLOR_RED    ,
    },
    {
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  , COLOR_BLACK  , COLOR_GREEN  ,
    },
    {
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  ,
        COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   , COLOR_BLACK  , COLOR_BLUE   ,
    },
    {
        COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_GREEN  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_RED    , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_BLUE   , COLOR_RED    ,
        COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_GREEN  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_RED    , COLOR_GREEN  ,
        COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_BLUE   , COLOR_RED    ,
        COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_GREEN  , COLOR_BLUE   ,
        COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_BLUE   , COLOR_RED    , COLOR_GREEN  , COLOR_RED    , COLOR_GREEN  ,
    },
};

#else

#error "TILE_WIDTH must be 6 or 8"

#endif